// كشف الروبوتات/العناكب من User-Agent
// يُستخدم في activity — يمنع إشعارات البوتات من العداد والتنبيه

const BOT_PATTERNS = [
  /googlebot/i,
  /bingbot/i,
  /slurp/i,
  /duckduckbot/i,
  /yandex/i,
  /baiduspider/i,
  /sogou/i,
  /exabot/i,
  /facebookexternalhit/i,
  /facebot/i,
  /twitterbot/i,
  /linkedinbot/i,
  /pinterest/i,
  /whatsapp/i,
  /telegrambot/i,
  /vkShare/i,
  /skypeuripreview/i,
  /discordbot/i,
  /slackbot/i,
  /viber/i,
  /line/i,
  /wechat/i,
  /tumblr/i,
  /redditbot/i,
  /pinterestbot/i,
  /quora/i,
  /instapaper/i,
  /tapatalk/i,
  /outbrain/i,
  /taboola/i,
  /admantx/i,
  /mediapartners-google/i,
  /adsbot-google/i,
  /AhrefsBot/i,
  /SemrushBot/i,
  /MJ12bot/i,
  /DotBot/i,
  /PetalBot/i,
  /rogerbot/i,
  /MozBot/i,
  /SeznamBot/i,
  /archive\.org_bot/i,
  /ia_archiver/i,
  /applebot/i,
  /pingdom/i,
  /uptimerobot/i,
  /monitoring/i,
  /crawler/i,
  /spider/i,
  /bot\b/i,
  /GPTBot/i,
  /ClaudeBot/i,
  /anthropic-ai/i,
  /ccbot/i,
  /diffbot/i,
  /scrapy/i,
  /python-requests/i,
  /curl\//i,
  /wget\//i,
  /headlesschrome/i,
  /phantomjs/i,
  /puppeteer/i,
  /playwright/i,
  /selenium/i,
  /metaprobe/i,
];

function isBot(ua) {
  if (!ua) return false;
  if (String(ua).trim().length === 0) return false;
  return BOT_PATTERNS.some((re) => re.test(ua));
}

module.exports = { isBot };
